name: Daily Internship Check

on:
  schedule:
    - cron: '0 13 * * 1-5'  # 8 AM EST / 5 AM PST, Mon–Fri
    - cron: '0 17 * * 1-5'  # 12 PM EST / 9 AM PST, Mon–Fri
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run internship scraper
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python internship.py
