name: Daily Internship Check

on:
  schedule:
    - cron: '0 14 * * *'  # 10:00 AM EST
    - cron: '0 22 * * *'  # 6:00 PM EST
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run internship scraper
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python internship.py
